[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=0
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=INTERCEPT50 v1.7
Config=
ExtPrg=
Message=
Romid=321
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=INTERCEPT50.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=INTMNU.s
file2=INFRM.s
file3=INTER.s
file4=INTERinputform.s
file5=INTERoutputform.s
file6=CONVARG.s
[Edit]
edit7=INTMNU.s
edit8=INFRM.s
edit9=INTER.s
edit10=INTERinputform.s
edit11=INTERoutputform.s
edit12=>CONVARG.s
