[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=1
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=1
InformHeight=50
EntryPointList=
Title=ROASB48 v1.4
Config=
ExtPrg=
Message=
Romid=323
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=ROASB48.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=RASBMNU.s
file2=RASBFRM.s
file3=ROASAMBA.s
file4=InptForm.s
file5=OutptForm.s
[Edit]
edit6=>RASBMNU.s
edit7=RASBFRM.s
edit8=ROASAMBA.s
edit9=InptForm.s
edit10=OutptForm.s
