[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=0
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=ISA50 v1.25
Config=
ExtPrg=
Message=
Romid=326
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=ISA50.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=GEOPO.s
file2=ISAT.s
file3=ISAP.s
file4=ISArho.s
file5=ISAa.s
file6=ISAform.s
file7=ISAFRM.s
file8=ISAMNU.s
[Edit]
edit9=GEOPO.s
edit10=ISAT.s
edit11=ISAP.s
edit12=ISArho.s
edit13=ISAa.s
edit14=ISAFRM.s
edit15=ISAform.s
edit16=>ISAMNU.s
