[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=0
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=CPONT50 v1.1
Config=
ExtPrg=
Message=
Romid=329
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=CPONT50.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=CPONTMNU.s
file2=GUIONTETP.s
file3=CONTETP.s
file4=InptForm.s
file5=OutptForm.s
[Edit]
edit6=>CPONTMNU.s
edit7=GUIONTETP.s
edit8=CONTETP.s
edit9=InptForm.s
edit10=OutptForm.s
