[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=1
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=ROAAB48 v1.4
Config=
ExtPrg=
Message=
Romid=325
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=ROAAB48.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=RAABMNU.s
file2=RAABFRM.s
file3=ROAAB.s
file4=InptForm.s
file5=OutptOutbndForm.s
file6=OutptInbndForm.s
[Edit]
edit7=RAABMNU.s
edit8=RAABFRM.s
edit9=ROAAB.s
edit10=>InptForm.s
edit11=OutptOutbndForm.s
edit12=OutptInbndForm.s
