[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=0
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=0
ProjectTab=0
InformHeight=50
EntryPointList=
Title=PNRVF50 v1.3
Config=
ExtPrg=
Message=
Romid=322
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=PNRVF50.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=PNRVFMNU.s
file2=PNRFRM.s
file3=PNRVF.s
file4=OutbndInptForm.s
file5=InbndInptForm.s
file6=OutbndOutptForm.s
file7=InbndOutptForm.s
file8=CONVARG.s
[Edit]
edit9=>PNRVFMNU.s
edit10=PNRFRM.s
edit11=PNRVF.s
edit12=OutbndInptForm.s
edit13=InbndInptForm.s
edit14=OutbndOutptForm.s
edit15=InbndOutptForm.s
edit16=CONVARG.s
