[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=1
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=ASPD48 v1.34
Config=
ExtPrg=
Message=
Romid=328
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=ASPD48.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=ASPDMNU.s
file2=CMACH.s
file3=CSAT.s
file4=TASMS.s
file5=CTAT.s
file6=ASPDFRM.s
file7=ASPDform.s
file8=FLD_M_MSGHNDLR.s
[Edit]
edit9=ASPDMNU.s
edit10=CMACH.s
edit11=CSAT.s
edit12=TASMS.s
edit13=CTAT.s
edit14=>ASPDFRM.s
edit15=ASPDform.s
edit16=FLD_M_MSGHNDLR.s
