[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=1
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=WIND48 v1.7
Config=
ExtPrg=
Message=
Romid=320
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=WIND48.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=WNDTR.s
file2=THGS.s
file3=CWVE.s
file4=CGVE.s
file5=CAVE.s
file6=WNDMNU.s
file7=WINDTRform.s
[Edit]
edit8=WNDTR.s
edit9=THGS.s
edit10=CWVE.s
edit11=CGVE.s
edit12=CAVE.s
edit13=WNDMNU.s
edit14=>WINDTRform.s
