[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=1
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=ROAMB48 v1.6
Config=
ExtPrg=
Message=
Romid=324
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=ROAMB48.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=RAMBMNU.s
file2=RAMBFRM.s
file3=ROAMB.s
file4=InptForm.s
file5=OutptOutbndForm.s
file6=OutptInbndForm.s
[Edit]
edit7=RAMBMNU.s
edit8=RAMBFRM.s
edit9=ROAMB.s
edit10=InptForm.s
edit11=OutptOutbndForm.s
edit12=>OutptInbndForm.s
