[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=1
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=INTERCEPT48 v1.7
Config=
ExtPrg=
Message=
Romid=321
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=INTERCEPT48.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=INTMNU.s
file2=INFRM.s
file3=INTER.s
file4=INTERinputform.s
file5=INTERoutputform.s
[Edit]
edit6=INTMNU.s
edit7=>INFRM.s
edit8=INTER.s
edit9=INTERinputform.s
edit10=INTERoutputform.s
