[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=0
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=ASPD v1.32
Config=
ExtPrg=
Message=
Romid=328
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=ASPD.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=ASPDMNU.s
file2=CMACH.s
file3=CSAT.s
file4=TASMS.s
file5=CTAT.s
file6=ASPDFRM.s
file7=ASPDform.s
[Edit]
edit8=ASPDMNU.s
edit9=CMACH.s
edit10=CSAT.s
edit11=TASMS.s
edit12=CTAT.s
edit13=ASPDFRM.s
edit14=>ASPDform.s
