[Main]
library=1
IncludeUserRPL=1
AutoLoad=1
Compress=0
Calc48=0
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=1
InformHeight=50
EntryPointList=
Title=WIND50 v1.7
Config=
ExtPrg=
Message=
Romid=320
Slot=0
Emu48Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files\Hewlett-Packard\Debug4x\Emu\\default 48GX.bin
Emu49Ram=C:\Documents and Settings\Dan Pitic\My Documents\Debug4x\Emu\default 50G.e49
FilePath=WIND50.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=CAVE.s
file2=CGVE.s
file3=CWVE.s
file4=THGS.s
file5=WNDTR.s
file6=WNDMNU.s
file7=WINDTRform.s
[Edit]
edit8=CAVE.s
edit9=CGVE.s
edit10=CWVE.s
edit11=THGS.s
edit12=WNDTR.s
edit13=>WNDMNU.s
edit14=WINDTRform.s
